In [3]:
import pandas as pd
from sympy.printing.pytorch import torch

data = pd.read_csv('house_tiny.csv')
print(data)

   Numrooms  Alley   Price
0       NaN  Prave  127500
1       2.0    NaN   10600
2       4.0    NaN  178100
3       NaN    NaN  140000

# Data preparation

In [5]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

   Numrooms  Alley_Prave  Alley_nan
0       NaN         True      False
1       2.0        False       True
2       4.0        False       True
3       NaN        False       True

In [6]:
inputs = inputs.fillna(inputs.mean())
inputs

   Numrooms  Alley_Prave  Alley_nan
0       3.0         True      False
1       2.0        False       True
2       4.0        False       True
3       3.0        False       True

In [11]:
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500.,  10600., 178100., 140000.], dtype=torch.float64))